verbose = false

[dstat]
prog = "dstat"
args = "-clmdny --tcp"

[redis]
host = "127.0.0.1"
port = 6379
# pass = "secret"

cmds = [
  "SET     dstat __json__",
#  "PUBLISH dstat mem:__used__,disk(in=__read__,out=__writ__)",
#  "ZADD    dstat/__host__/__%Y%m%d-%H__ CH __epoch__ __json__",
#  "EXPIRE  dstat/__host__/__%Y%m%d-%H__ 86400",
#  "SADD    dstat/__host__ __%Y%m%d-%H__",
]

[log]
interval_sec = 3
time_format = "%Y-%m-%d %H:%M:%S"
